import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { getThemeId, THEMES } from "../src/features/theme/themes";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(scriptDirectory, "../src/features/theme/themes.generated.css");
const defaultTheme = THEMES.find(({ scheme }) => scheme === "light");
const defaultDarkTheme = THEMES.find(({ scheme }) => scheme === "dark");
const hexColorPattern = /^#[0-9a-f]{6}(?:[0-9a-f]{2})?$/i;

if (!defaultTheme || !defaultDarkTheme) {
  throw new Error("Themes must include light and dark palettes for system mode.");
}

const themeIds = THEMES.map(getThemeId);
if (new Set(themeIds).size !== themeIds.length) {
  throw new Error("Theme names must produce unique slugs.");
}

for (const theme of THEMES) {
  for (const [token, color] of Object.entries(theme.colors)) {
    if (!hexColorPattern.test(color)) {
      throw new Error(`${theme.name}: ${token} must be a 6- or 8-digit hex color.`);
    }
  }
}

const variables = (colors: Record<string, string>) =>
  Object.entries(colors)
    .map(([name, value]) => `  --${name}: ${value};`)
    .join("\n");

const themeClass = (name: string, scheme: string, colors: Record<string, string>) =>
  `.${name} {\n  color-scheme: ${scheme};\n${variables(colors)}\n}`;

const darkThemeIds = THEMES.filter(({ scheme }) => scheme === "dark").map(getThemeId);

/**
 * shadcn/ui token reference (style: base-nova, baseColor: neutral).
 *
 * Ground truth for stock values: https://ui.shadcn.com/r/colors/neutral.json
 * (`cssVars.light` / `cssVars.dark`). Components consume these via Tailwind
 * utilities like `bg-card`, `border-input`, `text-muted-foreground`, wired up
 * in globals.css's `@theme inline` block.
 *
 * Our themes only define a reduced raw palette (see ThemeColors in
 * src/features/theme/themes.ts): background, foreground, surface,
 * surface-muted, primary, primary-foreground, secondary, muted-foreground,
 * destructive, border — plus optional per-theme "input"/"ring" overrides.
 * The :root block below maps every remaining shadcn token onto that palette.
 * A theme block can override any of these by defining the key itself
 * (e.g. Ink/Paper set input + ring to match stock exactly).
 *
 * Full token inventory and how each resolves:
 *
 * Core
 *   background                  = theme background
 *   foreground                  = theme foreground
 *   card                        → var(--surface)
 *   card-foreground             → var(--foreground)
 *   popover                     → var(--surface)
 *   popover-foreground          → var(--foreground)
 *   primary                     = theme primary
 *   primary-foreground          = theme primary-foreground
 *   secondary                   = theme secondary
 *   secondary-foreground        → var(--foreground)  (stock light: #171717 vs our #0a0a0a; negligible)
 *   muted                       → var(--secondary)
 *   muted-foreground            = theme muted-foreground
 *   accent                      → var(--secondary)
 *   accent-foreground           → var(--foreground)
 *   destructive                 = theme destructive
 *   border                      = theme border
 *   input                       → var(--secondary), overridable per theme
 *                                 (stock dark is translucent white/15%, stock light = border;
 *                                  Ink/Paper override to stay pixel-exact)
 *   ring                        → var(--primary), overridable per theme
 *                                 (stock: #737373 dark / #a3a3a3 light — a unique mid-gray;
 *                                  Ink/Paper override)
 *
 * Radius
 *   radius                      hardcoded below (0.8rem); globals.css derives
 *                               --radius-sm..--radius-4xl from it via calc().
 *
 * Charts (not emitted — no consumers yet; add per-theme chart-1..5 keys if
 * a component using chart colors is ever installed)
 *   chart-1..chart-5            undefined
 *
 * Sidebar (mapped even though unused today, so the ui/sidebar.tsx component
 * works if ever added)
 *   sidebar                     → var(--surface-muted)
 *   sidebar-foreground          → var(--foreground)
 *   sidebar-primary             → var(--primary)  (stock dark quirk: blue-600)
 *   sidebar-primary-foreground  → var(--primary-foreground)
 *   sidebar-accent              → var(--secondary)
 *   sidebar-accent-foreground    → var(--foreground)
 *   sidebar-border              → var(--border)
 *   sidebar-ring                → var(--primary)  (stock: same as ring)
 */
const css = `/* This file is generated by scripts/generate-themes.ts. Do not edit it directly. */

:root {
  --card: var(--surface);
  --card-foreground: var(--foreground);
  --popover: var(--surface);
  --popover-foreground: var(--foreground);
  --secondary-foreground: var(--foreground);
  --muted: var(--secondary);
  --accent: var(--secondary);
  --accent-foreground: var(--foreground);
  --input: var(--secondary);
  --ring: var(--primary);
  --sidebar: var(--surface-muted);
  --sidebar-foreground: var(--foreground);
  --sidebar-primary: var(--primary);
  --sidebar-primary-foreground: var(--primary-foreground);
  --sidebar-accent: var(--secondary);
  --sidebar-accent-foreground: var(--foreground);
  --sidebar-border: var(--border);
  --sidebar-ring: var(--primary);
  --radius: 0.8rem;
}

:root,
.light,
.${getThemeId(defaultTheme)} {
  color-scheme: light;
${variables(defaultTheme.colors)}
}

${THEMES.filter((theme) => theme !== defaultTheme && theme !== defaultDarkTheme)
  .map((theme) => themeClass(getThemeId(theme), theme.scheme, theme.colors))
  .join("\n\n")}

.dark,
.${getThemeId(defaultDarkTheme)} {
  color-scheme: dark;
${variables(defaultDarkTheme.colors)}
}

@custom-variant dark (&:is(.dark *, ${darkThemeIds.map((id) => `.${id} *`).join(", ")}));
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, css);
