import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { getThemeId, THEMES } from "../src/features/theme/themes";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(scriptDirectory, "../src/features/theme/themes.generated.css");
const defaultTheme = THEMES.find(({ scheme }) => scheme === "light");
const defaultDarkTheme = THEMES.find(({ scheme }) => scheme === "dark");
const hexColorPattern = /^#[0-9a-f]{6}(?:[0-9a-f]{2})?$/i;

if (!defaultTheme || !defaultDarkTheme) {
  throw new Error("Themes must include light and dark palettes for system mode.");
}

const themeIds = THEMES.map(getThemeId);
if (new Set(themeIds).size !== themeIds.length) {
  throw new Error("Theme names must produce unique slugs.");
}

for (const theme of THEMES) {
  for (const [token, color] of Object.entries(theme.colors)) {
    if (!hexColorPattern.test(color)) {
      throw new Error(`${theme.name}: ${token} must be a 6- or 8-digit hex color.`);
    }
  }
}

const variables = (colors: Record<string, string>) =>
  Object.entries(colors)
    .map(([name, value]) => `  --${name}: ${value};`)
    .join("\n");

const themeClass = (name: string, scheme: string, colors: Record<string, string>) =>
  `.${name} {\n  color-scheme: ${scheme};\n${variables(colors)}\n}`;

const darkThemeIds = THEMES.filter(({ scheme }) => scheme === "dark").map(getThemeId);
const css = `/* This file is generated by scripts/generate-themes.ts. Do not edit it directly. */

:root {
  --card: var(--surface);
  --card-foreground: var(--foreground);
  --popover: var(--surface);
  --popover-foreground: var(--foreground);
  --secondary-foreground: var(--foreground);
  --muted: var(--secondary);
  --accent: var(--secondary);
  --accent-foreground: var(--foreground);
  --input: var(--secondary);
  --ring: var(--primary);
  --sidebar: var(--surface-muted);
  --sidebar-foreground: var(--foreground);
  --sidebar-primary: var(--primary);
  --sidebar-primary-foreground: var(--primary-foreground);
  --sidebar-accent: var(--secondary);
  --sidebar-accent-foreground: var(--foreground);
  --sidebar-border: var(--border);
  --sidebar-ring: var(--primary);
  --radius: 0.625rem;
}

:root,
.light,
.${getThemeId(defaultTheme)} {
  color-scheme: light;
${variables(defaultTheme.colors)}
}

${THEMES.filter((theme) => theme !== defaultTheme && theme !== defaultDarkTheme)
  .map((theme) => themeClass(getThemeId(theme), theme.scheme, theme.colors))
  .join("\n\n")}

.dark,
.${getThemeId(defaultDarkTheme)} {
  color-scheme: dark;
${variables(defaultDarkTheme.colors)}
}

@custom-variant dark (&:is(.dark *, ${darkThemeIds.map((id) => `.${id} *`).join(", ")}));
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, css);
